#!/usr/bin/env python3
"""AppSec Customize — walk the three forcing questions, emit CUSTOMIZE.md.

Stdlib only. Validates the operator answered all three forcing questions
(language+runtime, top three vuln classes, deployment surface); refuses
otherwise. Writes <target>/CUSTOMIZE.md plus the 11-field contract.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

SLUG = "appsec-customize"

DEPLOYMENT_TO_L4 = {
    "ci-only":   {"chain_default": "L3", "patch_candidate": "L3", "rationale": "lint-only; no production mutation possible"},
    "staging":   {"chain_default": "L3", "patch_candidate": "L4", "rationale": "patch-candidate gated; chain skills stay L3"},
    "production":{"chain_default": "L3", "patch_candidate": "L4", "rationale": "patch-candidate with disable-model-invocation: true mandatory"},
}

DEFAULT_INPUT = {
    "ecosystem_name": "RustMicroserviceStack",
    "language": "rust",
    "runtime": "actix",
    "file_extensions": [".rs", ".toml"],
    "top_three_classes": [
        {"class": "unsafe-deserial", "rationale": "serde untagged enums can be coerced"},
        {"class": "use-after-free", "rationale": "concentrated in unsafe blocks; rare elsewhere"},
        {"class": "panic-in-handler", "rationale": "unwrap/expect in async handlers is a DoS vector"},
    ],
    "deployment_surface": "production",
    "target_path": "/tmp/rust-microservices",
}


def _validate(answers: dict):
    missing = []
    for key in ("ecosystem_name", "language", "runtime", "file_extensions", "top_three_classes", "deployment_surface"):
        if not answers.get(key):
            missing.append(key)
    if isinstance(answers.get("top_three_classes"), list) and len(answers["top_three_classes"]) != 3:
        missing.append("top_three_classes must contain exactly 3 entries")
    if answers.get("deployment_surface") not in DEPLOYMENT_TO_L4:
        missing.append("deployment_surface must be one of " + ", ".join(DEPLOYMENT_TO_L4.keys()))
    return missing


def _pattern_catalog(answers: dict):
    """Build a pattern catalog skeleton from the operator's top-three answers."""
    catalog = []
    for entry in answers.get("top_three_classes", []):
        cls = entry["class"]
        catalog.append({
            "rule_id": cls,
            "anchor_hint": "<provide regex / heuristic for " + cls + ">",
            "default_severity": "high",
        })
    return catalog


def _patch_recipes(answers: dict):
    """Recipe skeletons keyed by class."""
    recipes = []
    for entry in answers.get("top_three_classes", []):
        cls = entry["class"]
        recipes.append({
            "rule_id": cls,
            "one_line_fix": "<provide minimal-blast-radius fix for " + cls + ">",
            "verify_command": "<provide regression command for " + cls + ">",
        })
    return recipes


def _write_artifact(answers: dict, catalog, recipes, surface_meta):
    target_path = Path(answers.get("target_path") or ("/tmp/" + answers["ecosystem_name"]))
    artifact = target_path / "CUSTOMIZE.md"
    lines = [
        "# Customization plan: " + answers["ecosystem_name"],
        "",
        "Generated by USAP `appsec-customize` skill on " +
        datetime.now(timezone.utc).strftime("%Y-%m-%d") + ".",
        "",
        "## Language and runtime",
        "",
        "| Language | Runtime | File extensions |",
        "|---|---|---|",
        "| " + answers["language"] + " | " + answers["runtime"] + " | " +
        ", ".join(answers["file_extensions"]) + " |",
        "",
        "## Pattern catalog",
        "",
        "| rule_id | Regex / heuristic | Default severity |",
        "|---|---|---|",
    ]
    for e in catalog:
        lines.append("| `" + e["rule_id"] + "` | " + e["anchor_hint"] + " | " + e["default_severity"] + " |")

    lines += ["", "## Patch recipes", "", "| rule_id | One-line fix | Verify command |", "|---|---|---|"]
    for e in recipes:
        lines.append("| `" + e["rule_id"] + "` | " + e["one_line_fix"] + " | `" + e["verify_command"] + "` |")

    lines += [
        "",
        "## Deployment surface",
        "",
        "| Where it runs | Chain default level | patch-candidate level | Notes |",
        "|---|---|---|---|",
        "| " + answers["deployment_surface"] + " | " + surface_meta["chain_default"] + " | " +
        surface_meta["patch_candidate"] + " | " + surface_meta["rationale"] + " |",
        "",
        "## Regression-test discipline",
        "",
        "| Class | Minimum test |",
        "|---|---|",
    ]
    for e in recipes:
        lines.append("| `" + e["rule_id"] + "` | " + e["verify_command"] + " |")

    artifact.parent.mkdir(parents=True, exist_ok=True)
    artifact.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return artifact


def customize(answers: dict):
    missing = _validate(answers)
    if missing:
        return {
            "agent_slug": SLUG,
            "intent_type": "report",
            "action": "Refuse to plan — operator did not answer all three forcing questions.",
            "rationale": "Missing or invalid: " + ", ".join(missing),
            "confidence": 0.95,
            "severity": "informational",
            "key_findings": ["Forcing-question gap: " + m for m in missing],
            "evidence_references": [],
            "next_agents": ["threat-model"],
            "human_approval_required": False,
            "timestamp_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "affected_assets": [answers.get("ecosystem_name", "unknown")],
        }

    catalog = _pattern_catalog(answers)
    recipes = _patch_recipes(answers)
    surface_meta = DEPLOYMENT_TO_L4[answers["deployment_surface"]]
    artifact_path = _write_artifact(answers, catalog, recipes, surface_meta)

    classes = ", ".join(e["class"] for e in answers["top_three_classes"])
    key_findings = [
        "Language: " + answers["language"] + " + " + answers["runtime"] +
        "; file extensions: " + ", ".join(answers["file_extensions"]),
        "Top three classes: " + classes,
        "Deployment: " + answers["deployment_surface"] + " — patch-candidate level " + surface_meta["patch_candidate"],
        "Pattern catalog: " + str(len(catalog)) + " rule_id anchor skeletons (operator fills in regex)",
        "Regression discipline: " + str(len(recipes)) + " verify command skeletons (operator fills in)",
    ]

    return {
        "agent_slug": SLUG,
        "intent_type": "advise",
        "action": ("CUSTOMIZE.md plan for " + answers["ecosystem_name"] + " ready — hand off to threat-model."),
        "rationale": (
            "Operator answered all three forcing questions for a " +
            answers["language"] + "/" + answers["runtime"] + " stack deploying to " +
            answers["deployment_surface"] + ". " +
            "Top three classes: " + classes + ". " +
            "Deployment triggers patch-candidate at level " + surface_meta["patch_candidate"] + " (" +
            surface_meta["rationale"] + ")."
        ),
        "confidence": 0.85,
        "severity": "informational",
        "key_findings": key_findings,
        "evidence_references": [
            {"source": "operator", "ref": "forcing-questions",
             "quote": classes + " on " + answers["deployment_surface"]}
        ],
        "next_agents": ["threat-model"],
        "human_approval_required": False,
        "timestamp_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "affected_assets": [answers["ecosystem_name"]],
        "artifact_path": str(artifact_path),
    }


def _render_human(payload: dict) -> str:
    lines = [
        "BOTTOM LINE: " + payload["action"],
        "CONFIDENCE: %.2f" % payload["confidence"],
        "ARTIFACT: " + payload.get("artifact_path", "-"),
        "PLAN:",
    ]
    lines += ["  - " + f for f in payload["key_findings"]]
    lines.append("NEXT: " + " -> ".join(payload["next_agents"]))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--input", help="Path to a forcing-question answers JSON.")
    parser.add_argument("--output", choices=("json", "human"), default="json")
    args = parser.parse_args()
    if args.input:
        try:
            answers = json.loads(Path(args.input).read_text(encoding="utf-8"))
        except (FileNotFoundError, json.JSONDecodeError) as exc:
            print("error: %s" % exc, file=sys.stderr)
            return 2
    else:
        answers = DEFAULT_INPUT
    payload = customize(answers)
    if args.output == "json":
        print(json.dumps(payload, indent=2))
    else:
        print(_render_human(payload))
    return 0


if __name__ == "__main__":
    sys.exit(main())
